services:

  mysql:
    image: 'mysql:8.0.35'
    environment:
      - 'MYSQL_DATABASE=sample'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=sample'
    ports:
      - '33066:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=sample'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=sample'
    ports:
      - '54326:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  mysql_data:
