spring:
  application:
    name: multi-source-service
  datasource:
    hikari:
      main:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:54326/sample
        username: sample
        password: 1234
      sub:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:54327/sample
        username: sample
        password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
  #        show_sql: true # sql 로깅
  #        #        format_sql: true # SQL 문 정렬하여 출력
  #        highlight_sql: true # SQL 문 색 부여
  #        use_sql_comments: true # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 HINT 표시
  docker:
    compose:
      lifecycle-management: start_only # start_only, start_and_stop 옵션이 있으며, 스프링 종료 시 컨테이너 종료 여부를 결정할 수 있음
      start:
        command: up
      stop:
        command: down
        timeout: 1m
      #  batch:
      #    jdbc:
      #      platform: postgresql
      #      schema: classpath:org/springframework/batch/core/schema-postgresql.sql
      #      initialize-schema: always

decorator:
  datasource:
    p6spy:
      enable-logging: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true